import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { getCssText } from "@/styles";
import { globalStyles } from "@/styles/global";
import logoImg from "../assets/logo.svg"
import { Container, Header } from "@/styles/pages/app";
import Image from "next/image";

const roboto = Roboto({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  globalStyles()

  return (
    <html lang="en">
      <head>
        <style id="stitches" dangerouslySetInnerHTML={{ __html: getCssText() }} />
      </head>
      <body
        className={`${roboto.className} antialiased`}
      >
        <Container>
          <Header>
            <Image width={200} height={120} src={logoImg.src} alt="" />
          </Header>
          {children}
        </Container>
      </body>
    </html>
  );
}
